name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build backend container
      run: docker build . --file Dockerfile --tag bytes-backend:$(date +%s) && docker tag bytes-backend:$(date +%s) https://ghcr.io/rbrick/bytes-backend:latest
    - name: Build frontend container
      run: docker build ./frontend --file ./frontend/Dockerfile --tag bytes-frontend:$(date +%s) && docker tag bytes-frontend:$(date +%s) https://ghcr.io/rbrick/bytes-frontend:latest
    - name: Push backend container
      run: docker push ghcr.io/rbrick/bytes-backend:latest
    - name: Push frontend
      run: docker push ghcr.io/rbrick/bytes-frontend:latest