name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build backend container
      run: docker build . --file Dockerfile --tag bytes-backend:$(date +%s)  
    - name: Build frontend container
      run: docker build ./frontend --file ./frontend/Dockerfile --tag bytes-frontend:$(date +%s)
    - name: Push backend container
      run: docker push ghcr.io/rbrick/bytes-backend:latest
    - name: Push frontend
      run: docker push ghcr.io/rbrick/bytes-frontend:latest
